version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # Evita conflito com node_modules do host
    environment:
      - NODE_ENV=development
    command: npm run dev
